"use client";

import { useFormState, useFormStatus } from "react-dom";
import { suggestWorkout, SuggestWorkoutOutput } from "@/ai/flows/suggest-workout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, Sparkles } from "lucide-react";

async function suggestWorkoutAction(
  prevState: any,
  formData: FormData
): Promise<SuggestWorkoutOutput | { error: string }> {
  const workoutHistory = formData.get("workoutHistory") as string;
  const fitnessGoals = formData.get("fitnessGoals") as string;

  if (!workoutHistory || !fitnessGoals) {
    return { error: "Please fill out both fields." };
  }

  try {
    const result = await suggestWorkout({ workoutHistory, fitnessGoals });
    return result;
  } catch (e) {
    return { error: "Failed to get suggestion. Please try again." };
  }
}

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending}>
      {pending ? (
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
      ) : (
        <Sparkles className="mr-2 h-4 w-4" />
      )}
      Get Suggestion
    </Button>
  );
}

export default function AiSuggesterPage() {
  const [state, formAction] = useFormState(suggestWorkoutAction, null);

  return (
    <div className="grid gap-6 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle className="font-headline">AI Workout Suggester</CardTitle>
          <CardDescription>
            Describe your recent workouts and future goals to get a personalized
            workout plan generated by AI.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form action={formAction} className="space-y-4">
            <div className="grid w-full items-center gap-1.5">
              <Label htmlFor="workoutHistory">Your Workout History</Label>
              <Textarea
                id="workoutHistory"
                name="workoutHistory"
                placeholder="e.g., I've been doing full-body workouts 3 times a week, focusing on compound lifts like squats and bench presses."
                rows={4}
                required
              />
            </div>
            <div className="grid w-full items-center gap-1.5">
              <Label htmlFor="fitnessGoals">Your Fitness Goals</Label>
              <Textarea
                id="fitnessGoals"
                name="fitnessGoals"
                placeholder="e.g., I want to build muscle mass in my upper body and improve my overall strength."
                rows={4}
                required
              />
            </div>
            <SubmitButton />
          </form>
        </CardContent>
      </Card>
      
      <Card className="flex flex-col">
        <CardHeader>
          <CardTitle className="font-headline">Suggested Workout</CardTitle>
          <CardDescription>
            Your AI-generated workout plan will appear here.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex-grow">
          {state && 'suggestedWorkout' in state && (
            <div className="prose prose-sm dark:prose-invert whitespace-pre-wrap">
              {state.suggestedWorkout}
            </div>
          )}
          {state && 'error' in state && (
            <p className="text-destructive">{state.error}</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
